/**
 * Google Fonts integration service.
 *
 * Provides font search (from a curated list of popular families) and
 * font-buffer fetching.
 *
 * Font resolution uses a pre-generated manifest (`font-manifest.json`)
 * that maps font families to complete TTF URLs on fonts.gstatic.com.
 * The manifest is generated at build time by `docs/scripts/generate-font-manifest.ts`
 * using a spoofed User-Agent so Google returns complete TTF files (not
 * woff2 subsets).  This avoids needing a CORS proxy.
 *
 * For fonts not in the manifest, falls back to fetching the Google Fonts
 * CSS API directly (may return woff2 subset URLs with a browser UA).
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type FontCategory = 'serif' | 'sans-serif' | 'monospace' | 'display' | 'handwriting';

export interface GoogleFontFamily {
  family: string;
  category: FontCategory;
}

export interface GoogleFontBuffers {
  regular: Buffer;
  bold: Buffer | null;
  italic: Buffer | null;
  boldItalic: Buffer | null;
}

// ---------------------------------------------------------------------------
// Curated list of ~50 popular Google Fonts
// ---------------------------------------------------------------------------

const POPULAR_FONTS: GoogleFontFamily[] = [
  { family: 'Roboto', category: 'sans-serif' },
  { family: 'Open Sans', category: 'sans-serif' },
  { family: 'Lato', category: 'sans-serif' },
  { family: 'Montserrat', category: 'sans-serif' },
  { family: 'Oswald', category: 'sans-serif' },
  { family: 'Raleway', category: 'sans-serif' },
  { family: 'Poppins', category: 'sans-serif' },
  { family: 'Nunito', category: 'sans-serif' },
  { family: 'Playfair Display', category: 'serif' },
  { family: 'Merriweather', category: 'serif' },
  { family: 'Source Sans 3', category: 'sans-serif' },
  { family: 'Ubuntu', category: 'sans-serif' },
  { family: 'PT Sans', category: 'sans-serif' },
  { family: 'Noto Sans', category: 'sans-serif' },
  { family: 'Inter', category: 'sans-serif' },
  { family: 'Work Sans', category: 'sans-serif' },
  { family: 'Fira Sans', category: 'sans-serif' },
  { family: 'Quicksand', category: 'sans-serif' },
  { family: 'Barlow', category: 'sans-serif' },
  { family: 'Cabin', category: 'sans-serif' },
  { family: 'Arimo', category: 'sans-serif' },
  { family: 'Tinos', category: 'serif' },
  { family: 'Cousine', category: 'monospace' },
  { family: 'Roboto Slab', category: 'serif' },
  { family: 'Roboto Mono', category: 'monospace' },
  { family: 'Noto Serif', category: 'serif' },
  { family: 'PT Serif', category: 'serif' },
  { family: 'Libre Baskerville', category: 'serif' },
  { family: 'Crimson Text', category: 'serif' },
  { family: 'EB Garamond', category: 'serif' },
  { family: 'Lora', category: 'serif' },
  { family: 'Bitter', category: 'serif' },
  { family: 'Josefin Sans', category: 'sans-serif' },
  { family: 'Dancing Script', category: 'handwriting' },
  { family: 'Pacifico', category: 'handwriting' },
  { family: 'Caveat', category: 'handwriting' },
  { family: 'Satisfy', category: 'handwriting' },
  { family: 'Lobster', category: 'display' },
  { family: 'Bebas Neue', category: 'display' },
  { family: 'Abril Fatface', category: 'display' },
  { family: 'Righteous', category: 'display' },
  { family: 'Permanent Marker', category: 'display' },
  { family: 'Fira Code', category: 'monospace' },
  { family: 'Source Code Pro', category: 'monospace' },
  { family: 'JetBrains Mono', category: 'monospace' },
  { family: 'IBM Plex Mono', category: 'monospace' },
  { family: 'Space Mono', category: 'monospace' },
  { family: 'Inconsolata', category: 'monospace' },
  { family: 'DM Sans', category: 'sans-serif' },
  { family: 'Rubik', category: 'sans-serif' },
];



// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------

/**
 * Search the curated font list by query string.  The query is matched
 * case-insensitively against the family name.  An empty query returns
 * the full list.  Users can also type any Google Font family name that
 * isn't in the curated list — the fetcher will still attempt to
 * download it.
 */
export function searchGoogleFonts(query: string): GoogleFontFamily[] {
  const q = query.trim().toLowerCase();
  if (!q) return POPULAR_FONTS;
  return POPULAR_FONTS.filter((f) => f.family.toLowerCase().includes(q));
}

// ---------------------------------------------------------------------------
// Font manifest — pre-generated TTF URLs for popular Google Fonts.
// Generated by docs/scripts/generate-font-manifest.ts
// ---------------------------------------------------------------------------

type FontManifest = Record<string, Record<string, string>>;

let manifestPromise: Promise<FontManifest> | null = null;

/**
 * Load the font manifest (lazy, cached).  The manifest maps font family
 * names to variant keys ("normal-400", "normal-700", "italic-400",
 * "italic-700") with complete TTF URLs from fonts.gstatic.com.
 */
function loadManifest(): Promise<FontManifest> {
  if (!manifestPromise) {
    const url = `${import.meta.env.BASE_URL}font-manifest.json`;
    manifestPromise = fetch(url)
      .then((res) => {
        if (!res.ok) throw new Error(`Manifest fetch failed: ${res.status}`);
        return res.json() as Promise<FontManifest>;
      })
      .catch((err) => {
        console.warn('Could not load font manifest:', err);
        manifestPromise = null;          // allow retry
        return {} as FontManifest;
      });
  }
  return manifestPromise;
}

// ---------------------------------------------------------------------------
// In-memory cache
// ---------------------------------------------------------------------------

const fontCache = new Map<string, GoogleFontBuffers>();

// ---------------------------------------------------------------------------
// Fetch helpers
// ---------------------------------------------------------------------------

async function fetchFontBuffer(url: string): Promise<Buffer> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Font file fetch failed: ${res.status} ${url}`);
  const ab = await res.arrayBuffer();
  return Buffer.from(ab);
}

/**
 * Resolve TTF URLs for a font family's four variants.
 *
 * Strategy:
 * 1. Look up the pre-generated manifest (complete TTF URLs, no proxy needed).
 * 2. If the font isn't in the manifest, fall back to fetching CSS directly
 *    from fonts.googleapis.com (returns woff2 subset URLs with a browser UA).
 *
 * Returns a map of variant keys to URLs.
 */
async function resolveFontUrls(family: string): Promise<Record<string, string>> {
  // 1. Try the manifest (complete TTF files)
  const manifest = await loadManifest();
  if (manifest[family]) return manifest[family];

  // 2. Fallback: fetch CSS directly from Google Fonts (woff2 subset URLs)
  const encodedFamily = encodeURIComponent(family);
  const cssUrl =
    `https://fonts.googleapis.com/css2?family=${encodedFamily}:ital,wght@0,400;0,700;1,400;1,700`;
  const res = await fetch(cssUrl);
  if (!res.ok) throw new Error(`Font CSS fetch failed: ${res.status} for ${family}`);
  const css = await res.text();
  return parseFontFaceCss(css);
}

// ---------------------------------------------------------------------------
// CSS parsing helpers (fallback only — used for fonts not in the manifest)
// ---------------------------------------------------------------------------

function parseFontFaceCss(css: string): Record<string, string> {
  const variants: Record<string, string> = {};
  const blockRe = /@font-face\s*\{([^}]+)\}/g;
  let match: RegExpExecArray | null;

  while ((match = blockRe.exec(css)) !== null) {
    const block = match[1];
    const styleMatch = /font-style:\s*(\w+)/.exec(block);
    const weightMatch = /font-weight:\s*(\d+)/.exec(block);
    const urlMatch = /url\(([^)]+)\)/.exec(block);

    if (styleMatch && weightMatch && urlMatch) {
      const key = `${styleMatch[1]}-${weightMatch[1]}`;
      // Only keep the first URL for each variant (avoid woff2 subset dupes)
      if (!variants[key]) {
        variants[key] = urlMatch[1];
      }
    }
  }
  return variants;
}

// ---------------------------------------------------------------------------
// Main public API
// ---------------------------------------------------------------------------

/**
 * Fetch font buffers for all four variants of a Google Font family.
 *
 * Uses a pre-generated manifest (font-manifest.json) to resolve complete
 * TTF URLs from fonts.gstatic.com — no proxy required.  For fonts not in
 * the manifest, falls back to the Google Fonts CSS API directly.
 *
 * Results are cached in memory so repeated calls for the same family
 * return instantly.  Missing variants (e.g. a display font that has no
 * italic) are set to `null`; the `regular` variant always falls back
 * to whatever is available.
 */
export async function fetchGoogleFontBuffers(family: string): Promise<GoogleFontBuffers> {
  const cached = fontCache.get(family);
  if (cached) return cached;

  const urls = await resolveFontUrls(family);

  const regularUrl = urls['normal-400'];
  const boldUrl = urls['normal-700'];
  const italicUrl = urls['italic-400'];
  const boldItalicUrl = urls['italic-700'];

  // We must have at least one variant
  const fallbackUrl = regularUrl ?? Object.values(urls)[0];
  if (!fallbackUrl) {
    throw new Error(`No font variants found for "${family}"`);
  }

  // Fetch all available variants in parallel
  const [regular, bold, italic, boldItalic] = await Promise.all([
    fetchFontBuffer(fallbackUrl),
    boldUrl ? fetchFontBuffer(boldUrl) : Promise.resolve(null),
    italicUrl ? fetchFontBuffer(italicUrl) : Promise.resolve(null),
    boldItalicUrl ? fetchFontBuffer(boldItalicUrl) : Promise.resolve(null),
  ]);

  const result: GoogleFontBuffers = { regular, bold, italic, boldItalic };
  fontCache.set(family, result);
  return result;
}